### ISSUE TITLE
rename rootfs project with a new name rootfs-base 

### ISSUE THREAD

**Issue by allencloud** [sealerio/basefs#12]
Just now, I talked with @fanux about the correctness of this project naming.

In sealer, currently there is two kinds of rootfs:

* First, all ClusterImage will be downloaded and mounted locally, **the moutpoint is call rootfs**
* Second, this project is called rootfs, which contains quite plenty of static files, like docker, containerd scripts, and docker.tar and so on.

Since, we think that the first one is more proper to be called rootfs, then we need to change this project name.

Maybe `rootfs-base` ? 

@sealerio/sealer-maintainers

**Comment by kakaZhou719** [comment]
agree to rename, this repo is mainly used to build standard cluster image. how about rename it to `clusterimage-base` ?

**Comment by justadogistaken** [comment]
BaseFS?

**Comment by allencloud** [comment]
> BaseFS?

@justadogistaken I would like to use lowercase name, basefs? fs is different from rootfs. basefs could be one part of the rootfs.
