### ISSUE TITLE
auto build sealer ClusterImage using github action

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/basefs#20]
## Issue Description

Type: *feature request*

### Describe what feature you want

move github action configs yaml from sealer repo to this basefs repo .and it could  be triggered from issue comment.

**Comment by bxvs888** [comment]
./imagebuild v1.24.3 arm64

**Comment by imdingtalk** [comment]
/imagebuild --k8s-version=v1.24.4 --platform=amd64  --cri=containerd

**Comment by imdingtalk** [comment]
/imagebuild --k8s-version=v1.24.3 --platform=amd64 --cri=containerd

**Comment by bxvs888** [comment]
/imagebuild --k8s-version=v1.25.0 --platform=arm64 --cri=containerd

**Comment by bxvs888** [comment]
/imagebuild --k8s-version=v1.25.0 --platform=arm64 --buildName=registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes25

**Comment by imdingtalk** [comment]
/imagebuild --k8s-version=v1.24.5 --cri=containerd --platform=amd64 --buildName=index.docker.io/imdingtalk/kubernetes:v1.24.5 --push

**Comment by imdingtalk** [comment]
/imagebuild --k8s-version=v1.24.5 --cri=containerd --platform=amd64 --push

**Comment by imdingtalk** [comment]
/imagebuild --k8s-version=v1.24.5 --cri=containerd --platform=amd64 --push

**Comment by ricardolrl** [comment]
/imagebuild--k8s-version=v1.26.0--platform=amd64
