### ISSUE TITLE
[question] Why do kubeadm.yml.tmpl and kubeadm.yml exist together

### ISSUE THREAD

**Issue by fangzhengjin** [sealerio/basefs#52]
Why do kubeadm.yml.tmpl and kubeadm.yml exist together, and when will kubeadm.yml.tmpl be used in sealer?

**Comment by Stevent-fei** [comment]
The `.tmpl file will take effect` when `sealer run`.

**Comment by fangzhengjin** [comment]
I notice that the kubeadm.yml.tmpl and kubeadm.yml contents of the current repository are not exactly the same. Will the two files be merged when sealer run is executed? Whose priority is higher?

**Comment by Stevent-fei** [comment]
> I notice that the kubeadm.yml.tmpl and kubeadm.yml contents of the current repository are not exactly the same. Will the two files be merged when sealer run is executed? Whose priority is higher?

`kubeadm.yml.tmpl`

**Comment by fangzhengjin** [comment]
When the sealer runs, kubeadm.yml is merged with kubeadm.yml.tmpl, but the existing content in kubeadm.yml.tmpl is not overwritten. Am I correct?

**Comment by Stevent-fei** [comment]
> When the sealer runs, kubeadm.yml is merged with kubeadm.yml.tmpl, but the existing content in kubeadm.yml.tmpl is not overwritten. Am I correct?

yeah!

**Comment by fangzhengjin** [comment]
Thank you for your patient answer.
